version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=AMBEVDOTNET;Username=postgres;Password=admin
      - MongoDbSettings__ConnectionString=mongodb://localhost:27017
      - MongoDbSettings__DatabaseName=AMBEVDOTNET
      - RabbitMQ__Host=localhost

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: ambev_rabbitmq
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  postgres:
    image: "postgres:15"
    container_name: ambev_postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=AMBEVDOTNET
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: "mongo:6"
    container_name: ambev_mongodb
    hostname: localhost
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
